import assert from "node:assert/strict";
import { performance } from "node:perf_hooks";
import { readFile } from "node:fs/promises";
import pg from "pg";
import { NetworkRepository } from "../../services/providers/network-provider/src/repository.js";
import type { NetworkSqlClient, NetworkSqlPool, Row } from "../../services/providers/network-provider/src/types.js";

const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL is required");const pool=new pg.Pool({connectionString:url,max:8});const DATA_SCOPE="n01-n01-20260825t0101",DATASET_SCOPE="n01-acceptance";const adapter:NetworkSqlPool={async connect():Promise<NetworkSqlClient>{const client=await pool.connect();return{async query<T extends Row=Row>(text:string,values?:readonly unknown[]){const result=await client.query(text,values===undefined?undefined:[...values]);return{rows:result.rows as T[],rowCount:result.rowCount};},release:()=>client.release()};}};
try{
 const snapshot=await loadSnapshot(),repository=new NetworkRepository({pool:adapter,maximumMatrixPoints:64}),scope={dataScopeKey:DATA_SCOPE,datasetScopeKey:DATASET_SCOPE};
 const snapA={routingSnapshot:snapshot,location:{coordinates:[0.00025,0.02],crs:"EPSG:4326"},maxDistanceM:10_000,limit:8},snapB={routingSnapshot:snapshot,location:{coordinates:[0.00175,0.02],crs:"EPSG:4326"},maxDistanceM:10_000,limit:8};
 const left=asRow((await repository.execute("network.snap.point",snapA,scope,30_000)).output),right=asRow((await repository.execute("network.snap.point",snapB,scope,30_000)).output),start=asRow(asRow(array(left.candidates)[0]).state),destination=asRow(asRow(array(right.candidates)[0]).state);
 const snapTimes:number[]=[],shortestTimes:number[]=[],matrixTimes:number[]=[];
 for(let index=0;index<40;index++){let at=performance.now();await repository.execute("network.snap.point",index%2?snapA:snapB,scope,30_000);snapTimes.push(performance.now()-at);at=performance.now();const path=await repository.execute("network.path.shortest",{routingSnapshot:snapshot,start,destination,objective:"SHORTEST_DISTANCE",maximumSegments:1000,deadlineMs:30_000},scope,30_000);assert.equal(asRow(path.output).status,"COMPLETED");shortestTimes.push(performance.now()-at);if(index<20){at=performance.now();const matrix=await repository.execute("network.path.cost-matrix",{routingSnapshot:snapshot,points:[start,destination],objective:"SHORTEST_DISTANCE",deadlineMs:30_000},scope,30_000);assert.equal(array(asRow(matrix.output).entries).length,4);matrixTimes.push(performance.now()-at);}}
 const snapP95=p95(snapTimes),shortestP95=p95(shortestTimes),matrixP95=p95(matrixTimes);assert.ok(snapP95<250,`snap p95 ${snapP95}`);assert.ok(shortestP95<250,`shortest p95 ${shortestP95}`);assert.ok(matrixP95<500,`matrix p95 ${matrixP95}`);
 const n01=JSON.parse(await readFile("reports/gowm-v0.5/n01-runtime-n01-20260825t0101.json","utf8")) as {commands:Array<{command:string[];elapsedMs:number;status:string}>};const buildCommand=n01.commands.find(item=>item.command.some(part=>part.endsWith("network-topology-runtime-client.js")));assert.equal(buildCommand?.status,"PASS");
 process.stdout.write(`${JSON.stringify({result:"GOWM_V05_ROUTING_PERFORMANCE_PASS",samples:{snap:40,shortest:40,matrix:20},snapP95Ms:round(snapP95),shortestP95Ms:round(shortestP95),matrix2x2P95Ms:round(matrixP95),targetsMs:{snap:250,shortest:250,matrix:500},boundedMatrixEntries:4,graphBuildGateElapsedMs:buildCommand?.elapsedMs,graphBuildEvidence:"n01-runtime-n01-20260825t0101.json",datasetClass:"S/M_ACCEPTANCE_FIXTURE"},null,2)}\n`);
}finally{await pool.end();}
async function loadSnapshot():Promise<Row>{const client=await pool.connect();try{await client.query("BEGIN");await client.query("SELECT gowm_network_v1.set_scope($1,$2)",[DATA_SCOPE,DATASET_SCOPE]);const graph=(await client.query("SELECT graph_version,content_hash,dataset_version FROM gowm_network_v1.graph_version WHERE graph_version='p01-20260825t0610'")).rows[0],profile=(await client.query("SELECT travel.version AS travel_version,cost.version AS cost_version,cost.content_hash FROM gowm_network_v1.travel_profile travel JOIN gowm_network_v1.cost_profile cost USING(travel_profile_version_id) WHERE travel.profile_key='p01-road-p01-20260825t0610' AND cost.profile_key='p01-cost-p01-20260825t0610'")).rows[0],condition=(await client.query("SELECT condition_snapshot_id::text,content_hash FROM gowm_network_v1.condition_snapshot WHERE graph_version_id=(SELECT graph_version_id FROM gowm_network_v1.graph_version WHERE graph_version='p01-20260825t0610') AND source_snapshot_version='baseline'")).rows[0];await client.query("COMMIT");return{networkDatasetVersion:graph.dataset_version,graphVersion:graph.graph_version,travelProfileVersion:profile.travel_version,costProfileVersion:profile.cost_version,conditionSnapshotId:condition.condition_snapshot_id,graphContentHash:graph.content_hash,costContentHash:profile.content_hash,conditionContentHash:condition.content_hash};}catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}}
function p95(values:number[]){return [...values].sort((a,b)=>a-b)[Math.ceil(values.length*0.95)-1]??0;}function round(value:number){return Number(value.toFixed(3));}function array(value:unknown):unknown[]{if(!Array.isArray(value))throw new Error("array expected");return value;}function asRow(value:unknown):Row{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("object expected");return value as Row;}
