import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { readdir, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import pg from "pg";

const source=process.env.DATABASE_ADMIN_URL;if(!source)throw new Error("DATABASE_ADMIN_URL is required");const adminUrl=new URL(source);adminUrl.pathname="/postgres";const admin=new pg.Pool({connectionString:adminUrl.toString(),max:1});const suffix=randomUUID().replaceAll("-","").slice(0,12),freshName=`gowm_v05_fresh_${suffix}`,upgradeName=`gowm_v05_upgrade_${suffix}`;const files=(await readdir(resolve("database/migrations"))).filter(name=>/^\d{3}_.+\.sql$/u.test(name)).sort();assert.equal(files.length,47);
try{
 await create(freshName);await create(upgradeName);const fresh=pool(freshName),upgrade=pool(upgradeName);
 try{
  await applyThrough(fresh,47);await applyThrough(fresh,47);assert.equal(await migrationCount(fresh),47);await assertions(fresh);await rollbackProbe(fresh);
  await applyThrough(upgrade,32);await upgrade.query("INSERT INTO data_scope(scope_key,operational_domain,description) VALUES('v05-upgrade-preserved','TEST','preserved v0.4 row')");const before=await upgrade.query<{count:number}>("SELECT count(*)::integer AS count FROM data_scope");await applyThrough(upgrade,47);const after=await upgrade.query<{count:number}>("SELECT count(*)::integer AS count FROM data_scope");assert.equal(after.rows[0]!.count,before.rows[0]!.count);assert.equal((await upgrade.query<{count:number}>("SELECT count(*)::integer AS count FROM data_scope WHERE scope_key='v05-upgrade-preserved'")).rows[0]!.count,1);assert.equal(await migrationCount(upgrade),47);assert.ok((await upgrade.query("SELECT to_regclass('route_planner_runtime.route_query_result_reference') AS relation")).rows[0]?.relation);
  process.stdout.write(`${JSON.stringify({result:"GOWM_V05_MIGRATION_PASS",migrationCount:47,assertionCount:32,fresh:"PASS",v04ToV05:"PASS_PRESERVED",checksumRepeat:"PASS",failedMigrationRollback:"PASS"},null,2)}\n`);
 }finally{await Promise.allSettled([fresh.end(),upgrade.end()]);}
}finally{await drop(freshName).catch(()=>undefined);await drop(upgradeName).catch(()=>undefined);await admin.end();}

async function applyThrough(target:pg.Pool,maximum:number){await target.query("CREATE TABLE IF NOT EXISTS schema_migration(version text PRIMARY KEY,checksum text NOT NULL,applied_at timestamptz NOT NULL DEFAULT clock_timestamp())");for(const file of files.filter(name=>Number(name.slice(0,3))<=maximum)){const raw=await readFile(resolve("database/migrations",file),"utf8"),sql=raw.replaceAll(":ANALYSIS_SRID","32650").replaceAll(":TRACKLET_MAX_TIME_GAP_MS","10000").replaceAll(":TRACKLET_MAX_DISTANCE_GAP_M","250").replaceAll(":TRACKLET_MAX_REQUIRED_SPEED_MPS","80"),checksum=createHash("sha256").update(sql).digest("hex"),existing=await target.query<{checksum:string}>("SELECT checksum FROM schema_migration WHERE version=$1",[file]);if(existing.rows[0]){assert.equal(existing.rows[0].checksum,checksum);continue;}await target.query(sql);await target.query("INSERT INTO schema_migration(version,checksum) VALUES($1,$2)",[file,checksum]);}}
async function assertions(target:pg.Pool){const tests=(await readdir(resolve("database/tests"))).filter(name=>/^\d{3}_.+_assertions\.sql$/u.test(name)).sort();assert.equal(tests.length,32);for(const file of tests){const sql=(await readFile(resolve("database/tests",file),"utf8")).split(/\r?\n/u).filter(line=>!line.trimStart().startsWith("\\")).join("\n");await target.query(sql);}}
async function rollbackProbe(target:pg.Pool){await assert.rejects(target.query("BEGIN; CREATE TABLE v05_partial_probe(id integer); SELECT * FROM v05_missing_relation; COMMIT;"));assert.equal((await target.query("SELECT to_regclass('public.v05_partial_probe')::text AS relation")).rows[0]?.relation,null);}
async function migrationCount(target:pg.Pool){return (await target.query<{count:number}>("SELECT count(*)::integer AS count FROM schema_migration")).rows[0]?.count??0;}function pool(name:string){const url=new URL(adminUrl);url.pathname=`/${name}`;return new pg.Pool({connectionString:url.toString(),max:2});}async function create(name:string){assert.match(name,/^[a-z0-9_]+$/u);await admin.query(`CREATE DATABASE ${name}`);}async function drop(name:string){assert.match(name,/^[a-z0-9_]+$/u);await admin.query("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1 AND pid<>pg_backend_pid()",[name]);await admin.query(`DROP DATABASE IF EXISTS ${name}`);}
