import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Pool } from "pg";
import { getContractSchema, getContractSchemaHash, type CapabilityDescriptor, type GatewayExecuteRequest, type WorldQueryPlanV2Node, type WorldQuerySubmission } from "../../packages/platform/contract-runtime/src/index.js";
import { createProviderRuntime, sha256, type ProviderOperation } from "../../packages/platform/provider-sdk/src/index.js";
import { CapabilityRegistry, DirectExecutionService, InProcessProviderClient, MemoryAuditSink, MemoryGatewayIdempotencyStore, MemoryQueryPlanStore, ProviderCircuitBreaker, QueryPlanValidator, WorldQueryRuntime, type GatewayPrincipal } from "../../services/gateway/world-capability-gateway/src/index.js";
import { createNetworkProvider } from "../../services/providers/network-provider/src/provider.js";
import type { NetworkSqlClient, NetworkSqlPool, Row } from "../../services/providers/network-provider/src/types.js";
import { createRoutePlanningProvider } from "../../services/providers/route-planning-provider/src/provider.js";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"../..");const runId=required("GOWM_V05_RUN_ID"),project=required("GOWM_V05_COMPOSE_PROJECT"),database=process.env.GOWM_G00_DATABASE??"gowm_v05_r03_20260825t1040";
if(process.env.ALLOW_GOWM_GATEWAY_E2E!=="YES")throw new Error("Set ALLOW_GOWM_GATEWAY_E2E=YES");
const DATA_SCOPE="n01-n01-20260825t0101",DATASET_SCOPE="n01-acceptance",role=`g00_${runId.replaceAll("-","_")}`,password=createHash("sha256").update(`${project}:${runId}:gateway`).digest("hex"),proxy=`gowm-${runId}-gateway-proxy`;
const env={...process.env,COMPOSE_PROJECT_NAME:project,POSTGRES_PASSWORD:process.env.POSTGRES_PASSWORD??"gowm_v05_local_test",STAS_DB_PASSWORD:process.env.STAS_DB_PASSWORD??"gowm_v05_stas_local_test"};const evidence:{phase:string;runId:string;database:string;status:"RUNNING"|"PASS"|"FAIL";commands:Row[];summary:Row|null;errors:string[]}={phase:"G00",runId,database,status:"RUNNING",commands:[],summary:null,errors:[]};
function docker(args:string[],shown=args):string{const started=Date.now();try{const value=execFileSync("docker",args,{cwd:root,env,encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();evidence.commands.push({command:["docker",...shown],status:"PASS",elapsedMs:Date.now()-started});return value;}catch(error){evidence.commands.push({command:["docker",...shown],status:"FAIL",elapsedMs:Date.now()-started});throw error;}}
async function save(){await mkdir(resolve(root,"reports/gowm-v0.5"),{recursive:true});await writeFile(resolve(root,`reports/gowm-v0.5/g00-runtime-${runId}.json`),`${JSON.stringify(evidence,null,2)}\n`);}
let roleMade=false,proxyMade=false;let pool:Pool|undefined;
try{
 const container=docker(["compose","ps","--quiet","postgres"]),networks=JSON.parse(docker(["inspect","--format","{{json .NetworkSettings.Networks}}",container])) as Row,networkName=Object.keys(networks)[0];if(!networkName)throw new Error("network unavailable");
 docker(["compose","exec","--no-TTY","postgres","psql","--username","gowm","--dbname",database,"--set","ON_ERROR_STOP=on","--command",`CREATE ROLE ${role} LOGIN PASSWORD '${password}'; GRANT network_provider,route_planner_provider TO ${role}`],["compose","exec","postgres","psql",`<create ${role} redacted>`]);roleMade=true;
 const proxyScript="import net from 'node:net';net.createServer(c=>{const u=net.connect(5432,'postgres');c.pipe(u).pipe(c);const x=()=>{c.destroy();u.destroy()};c.on('error',x);u.on('error',x)}).listen(5432,'0.0.0.0')";docker(["run","--detach","--name",proxy,"--network",networkName,"--publish","127.0.0.1::5432","node:22-bookworm","node","--input-type=module","--eval",proxyScript],["run","--detach","--name",proxy,"--network",networkName,"--publish","127.0.0.1::5432","node:22-bookworm","<fixed proxy>"]);proxyMade=true;
 const port=Number(docker(["inspect","--format","{{(index (index .NetworkSettings.Ports \"5432/tcp\") 0).HostPort}}",proxy]));pool=new Pool({host:"127.0.0.1",port,database,user:role,password,max:8,connectionTimeoutMillis:10_000});pool.on("error",()=>undefined);
 const adapter:NetworkSqlPool={async connect():Promise<NetworkSqlClient>{const client=await pool!.connect();return{async query<T extends Row=Row>(text:string,values?:readonly unknown[]){const result=await client.query(text,values===undefined?undefined:[...values]);return{rows:result.rows as T[],rowCount:result.rowCount};},release:()=>client.release()};}};
 const snapshot=await loadSnapshot(pool),networkProvider=createNetworkProvider({pool:adapter}),routeProvider=createRoutePlanningProvider({pool:adapter}),stateProvider=createStateProvider();const registry=new CapabilityRegistry();
 register(registry,networkProvider.runtime,"network",35101);register(registry,routeProvider.runtime,"route",35102);register(registry,stateProvider,"state",35103);
 const direct=new DirectExecutionService({registry,circuits:new ProviderCircuitBreaker(),idempotency:new MemoryGatewayIdempotencyStore(),audit:new MemoryAuditSink(),gatewayId:"g00-gateway",policyVersion:"g00/1",attestationIssuer:"g00-gateway"});
 const principal:GatewayPrincipal={principalRef:"principal:g00",authenticationMethod:"RUNTIME_ACCEPTANCE",authenticatedAt:new Date(Date.now()-1000).toISOString(),dataScopeClaim:DATA_SCOPE,datasetScopeClaim:DATASET_SCOPE};
 const snapInput={routingSnapshot:snapshot,location:position(0.00025,0.02),maxDistanceM:10_000,limit:8};const snap=await direct.execute("network.snap.point",requestFor(registry,"network.snap.point",snapInput,`${runId}:snap`,30_000,"MEDIUM"),principal);assert(asRow(snap.result.output?.value).status!=="UNREACHABLE","Gateway snap failed");
 const routeInput={requestId:`${runId}-route`,routingSnapshot:snapshot,start:position(0.00025,0.02),destination:position(0.00175,0.02),travelProfile:"1",costProfile:"1",objective:"SHORTEST_DISTANCE",deadlineMs:30_000};const route=await direct.execute("route.plan",requestFor(registry,"route.plan",routeInput,`${runId}:route`,60_000,"HIGH"),principal);assert(asRow(route.result.output?.value).status==="COMPLETED","Gateway route failed");
 const wrong=requestFor(registry,"route.plan",routeInput,`${runId}:wrong`,60_000,"HIGH");wrong.inputSchemaHash=`sha256:${"0".repeat(64)}`;let mismatch=false;try{await direct.execute("route.plan",wrong,principal);}catch(error){mismatch=isRow(error)&&error.code==="SCHEMA_MISMATCH";}assert(mismatch,"Gateway schema mismatch did not fail closed");
 const store=new MemoryQueryPlanStore(),runtime=new WorldQueryRuntime({validator:new QueryPlanValidator(registry),directExecution:direct,store,autoRunAsync:false});const submission=dagSubmission(registry,routeInput,runId);const completed=await runtime.submit(submission,principal,"SYNC");assert(completed.result?.status==="COMPLETED",`typed route/verify DAG failed: ${JSON.stringify(completed.result)}`);
 const restarted=new WorldQueryRuntime({validator:new QueryPlanValidator(registry),directExecution:direct,store,autoRunAsync:false});const replay=await restarted.submit(structuredClone(submission),principal,"SYNC");assert(replay.replayed&&sha256(replay.result)===sha256(completed.result),"Gateway restart replay failed");
 const asyncSubmission=dagSubmission(registry,{...routeInput,requestId:`${runId}-async`},`${runId}-async`);const queued=await runtime.submit(asyncSubmission,principal,"ASYNC");assert(queued.job.status==="QUEUED","large route was not queued");const cancelled=await runtime.cancel(asyncSubmission.plan.queryId,principal);assert(cancelled?.status==="CANCELLED","Gateway cancellation failed");
 const health=await registry.health();assert(health["gowm.network"]?.ready===true&&health["gowm.route-planning"]?.ready===true,"provider health isolation failed");
 evidence.summary={registeredProviders:Object.keys(health).sort(),directSnapStatus:asRow(snap.result.output?.value).status,directRouteStatus:asRow(route.result.output?.value).status,typedDagStatus:completed.result?.status,schemaMismatch:"FAIL_CLOSED",asyncInitialStatus:queued.job.status,cancelStatus:cancelled?.status,restartReplay:replay.replayed,resultRegistryReference:asRow(route.result.output?.value).queryResultReferenceKey};evidence.status="PASS";
 await pool.end();pool=undefined;docker(["rm","--force",proxy]);proxyMade=false;docker(["compose","exec","--no-TTY","postgres","psql","--username","gowm","--dbname","postgres","--command",`DROP ROLE ${role}`]);roleMade=false;await save();process.stdout.write(`GOWM_NETWORK_ROUTING_GATEWAY_PASS ${runId} ${database}\n`);
}catch(error){evidence.status="FAIL";evidence.errors.push(String(error instanceof Error?error.stack??error.message:error));await save();throw error;}finally{await pool?.end().catch(()=>undefined);if(proxyMade)try{docker(["rm","--force",proxy]);}catch{}if(roleMade)try{docker(["compose","exec","--no-TTY","postgres","psql","--username","gowm","--dbname","postgres","--command",`DROP ROLE IF EXISTS ${role}`]);}catch{}}

function register(registry:CapabilityRegistry,runtime:{manifest:()=>unknown;execute:unknown}|any,label:string,port:number){registry.register({approvalId:`g00-${label}`,approved:true,endpoint:new URL(`http://127.0.0.1:${port}/`),client:new InProcessProviderClient(runtime),manifest:runtime.manifest});}
function requestFor(registry:CapabilityRegistry,operationId:string,input:Row,idempotencyKey:string,timeoutMs:number,cost:"MEDIUM"|"HIGH"):GatewayExecuteRequest{const descriptor=registry.resolve(operationId,"1.0",true).descriptor;return{requestVersion:"1.0",requestId:`gateway_${idempotencyKey.replaceAll(":","_")}`,idempotencyKey,operationVersion:"1.0",inputSchemaHash:descriptor.inputSchemaHash,outputSchemaHash:descriptor.outputSchemaHash,input,executionPolicy:{deadlineAt:new Date(Date.now()+timeoutMs).toISOString(),maximumResultBytes:descriptor.limits.maximumOutputBytes??16_777_216,...(descriptor.limits.maximumRows===undefined?{}:{maximumRows:descriptor.limits.maximumRows}),...(descriptor.limits.maximumCandidates===undefined?{}:{maximumCandidates:descriptor.limits.maximumCandidates}),maximumCostClass:cost,preferredExecution:"SYNC"}};}
function createStateProvider(){const routeSchema=getContractSchema("urn:gowm:v0.5:route-planning-request"),hash="sha256:0cdee0b4a503099aef05e738a323ae57414c7f0c9cdba7997f86e89ed045da67" as const;const descriptor:CapabilityDescriptor={operationId:"world.get-current-state",operationVersion:"1.0",semanticRole:"FOUNDATION_DATA_QUERY",dataBinding:"WORLD_SNAPSHOT_BOUND",resultSemantics:"DATA_QUERY",executionBindings:["SYNC_HTTP"],criticalPathPolicy:"REMOTE_ONLY",maturity:"STABLE",inputSchemaUri:"urn:gowm:v0.5:route-planning-request",inputSchemaHash:hash,outputSchemaUri:"urn:gowm:v0.5:route-planning-request",outputSchemaHash:hash,scopePolicy:"DATA_SCOPE_REQUIRED",execution:{mode:"SYNC",defaultTimeoutMs:1_000,maximumTimeoutMs:30_000,costClass:"MEDIUM"},limits:{maximumInputBytes:1_048_576,maximumOutputBytes:1_048_576,maximumRows:1,maximumCandidates:1},snapshotPolicy:{dataSnapshot:"REQUIRED",computeSnapshot:"REQUIRED"},ports:{inputs:[{name:"request",schemaUri:"urn:gowm:v0.5:route-planning-request",schemaHash:hash,valueKind:"ANY",unitSemantics:"UNSPECIFIED"}],outputs:[{name:"result",schemaUri:"urn:gowm:v0.5:route-planning-request",schemaHash:hash,valueKind:"ANY",unitSemantics:"UNSPECIFIED"}]}};const operation:ProviderOperation={descriptor,inputSchema:routeSchema,outputSchema:routeSchema,inputSchemaLockHash:hash,outputSchemaLockHash:hash,method:{engine:"GOWM",engineVersion:"0.5",methodId:"world-current-state-route-fixture",methodVersion:"1.0"},async handle(input){return{status:"COMPLETED",value:input,dataSnapshot:{consistency:"PINNED",capturedAt:new Date().toISOString(),scopeDigest:sha256({scope:DATA_SCOPE}),resources:[{referenceKey:{namespace:"gowm",kind:"DATASET",id:`wrf_${"a".repeat(32)}`,version:"1"},authority:"GOWM",pinning:"PINNED",digest:sha256({fixture:"g00-state"})}]},consumption:{rows:1,candidates:1},warnings:[],changes:{repairApplied:false,typeChanged:false}};}};return createProviderRuntime({manifest:{providerProtocolVersion:"1.0",provider:{providerId:"gowm.world-state-route-input",providerVersion:"1.0.0",owner:"gowm-platform",implementationDigest:sha256({fixture:"g00"}),sourceRef:"urn:gowm:source:g00:world-state"},endpoints:{manifest:"/v1/manifest",liveness:"/health/live",readiness:"/health/ready",execute:"/v1/operations/{operationId}:execute",job:"/v1/jobs/{jobId}"},capabilities:[descriptor]},operations:[operation],policyVersion:"g00-state/1",policyDigest:sha256({policy:"g00-state/1"})});}
function dagSubmission(registry:CapabilityRegistry,routeInput:Row,suffix:string):WorldQuerySubmission{const state=registry.resolve("world.get-current-state","1.0",true).descriptor,route=registry.resolve("route.plan","1.0",true).descriptor,verify=registry.resolve("route.verify","1.0",true).descriptor;const port=(value:CapabilityDescriptor["ports"]["inputs"][number])=>({schemaUri:value.schemaUri,schemaHash:value.schemaHash,valueKind:value.valueKind,unitSemantics:value.unitSemantics});const node=(nodeId:string,descriptor:CapabilityDescriptor,inputs:WorldQueryPlanV2Node["inputs"]):WorldQueryPlanV2Node=>({nodeId,operation:{operationId:descriptor.operationId,operationVersion:descriptor.operationVersion,inputSchemaHash:descriptor.inputSchemaHash,outputSchemaHash:descriptor.outputSchemaHash},inputs,failurePolicy:"FAIL_FAST",budget:{maximumRows:descriptor.limits.maximumRows??100_000,maximumCandidates:descriptor.limits.maximumCandidates??128,maximumOutputBytes:descriptor.limits.maximumOutputBytes??16_777_216,maximumExecutionMs:Math.min(60_000,descriptor.execution.maximumTimeoutMs)}});const nodes=[node("state",state,{request:{kind:"LITERAL",port:port(state.ports.inputs[0]!),value:routeInput}}),node("route",route,{request:{kind:"NODE_OUTPUT",port:port(route.ports.inputs[0]!),nodeId:"state",outputPort:"result"}}),node("verify",verify,{request:{kind:"NODE_OUTPUT",port:port(verify.ports.inputs[0]!),nodeId:"route",outputPort:"result"}})];return{requestId:`g00-request-${suffix}`,idempotencyKey:`g00-idem-${suffix}`,parameterSchemaHash:getContractSchemaHash("world-query-parameters.schema.json"),parameters:{},plan:{queryPlanVersion:"2.0",queryId:`g00-query-${suffix}`,nodes,outputs:[{name:"verification",binding:{kind:"NODE_OUTPUT",nodeId:"verify",outputPort:"result",port:port(verify.ports.outputs[0]!)}}],budgets:{maximumNodes:3,maximumDepth:3,maximumRows:200_001,maximumCandidates:257,maximumOutputBytes:34_603_008,maximumExecutionMs:150_000}}};}
async function loadSnapshot(target:Pool):Promise<Row>{const client=await target.connect();try{await client.query("BEGIN");await client.query("SELECT gowm_network_v1.set_scope($1,$2)",[DATA_SCOPE,DATASET_SCOPE]);const graph=(await client.query("SELECT graph_version,content_hash,dataset_version FROM gowm_network_v1.graph_version WHERE graph_version='p01-20260825t0610'")).rows[0],profile=(await client.query("SELECT travel.version AS travel_version,cost.version AS cost_version,cost.content_hash FROM gowm_network_v1.travel_profile travel JOIN gowm_network_v1.cost_profile cost USING(travel_profile_version_id) WHERE travel.profile_key='p01-road-p01-20260825t0610' AND cost.profile_key='p01-cost-p01-20260825t0610'")).rows[0],condition=(await client.query("SELECT condition_snapshot_id::text,content_hash FROM gowm_network_v1.condition_snapshot WHERE graph_version_id=(SELECT graph_version_id FROM gowm_network_v1.graph_version WHERE graph_version='p01-20260825t0610') AND source_snapshot_version='baseline'")).rows[0];await client.query("COMMIT");return{networkDatasetVersion:graph.dataset_version,graphVersion:graph.graph_version,travelProfileVersion:profile.travel_version,costProfileVersion:profile.cost_version,conditionSnapshotId:condition.condition_snapshot_id,graphContentHash:graph.content_hash,costContentHash:profile.content_hash,conditionContentHash:condition.content_hash};}catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}}
function position(x:number,y:number):Row{return{coordinates:[x,y],crs:"EPSG:4326"};}function required(name:string){const value=process.env[name];if(!value)throw new Error(`${name} required`);return value;}function isRow(value:unknown):value is Row{return Boolean(value)&&typeof value==="object"&&!Array.isArray(value);}function asRow(value:unknown):Row{if(!isRow(value))throw new Error("object expected");return value;}function assert(value:unknown,message:string):asserts value{if(!value)throw new Error(message);}
