import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Pool } from "pg";
import type { ProviderExecutionRequest } from "../../packages/platform/contract-runtime/src/index.js";
import { sha256 } from "../../packages/platform/provider-sdk/src/index.js";
import { createRoutePlanningProvider } from "../../services/providers/route-planning-provider/src/provider.js";
import type { NetworkSqlClient, NetworkSqlPool, Row } from "../../services/providers/network-provider/src/types.js";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"../.."); const DATA_SCOPE="n01-n01-20260825t0101", DATASET_SCOPE="n01-acceptance";
const runId=required("GOWM_V05_RUN_ID"), project=required("GOWM_V05_COMPOSE_PROJECT"), database=process.env.GOWM_R02_DATABASE??"gowm_v05_r00_20260825t0640";
if(process.env.ALLOW_GOWM_ROUTE_VERIFIER_GATE!=="YES")throw new Error("Set ALLOW_GOWM_ROUTE_VERIFIER_GATE=YES");
const role=`r02_${runId.replaceAll("-","_")}`, password=createHash("sha256").update(`${project}:${runId}:verifier`).digest("hex"), proxy=`gowm-${runId}-verifier-proxy`;
const env={...process.env,COMPOSE_PROJECT_NAME:project,POSTGRES_PASSWORD:process.env.POSTGRES_PASSWORD??"gowm_v05_local_test",STAS_DB_PASSWORD:process.env.STAS_DB_PASSWORD??"gowm_v05_stas_local_test"};
const evidence:{phase:string;runId:string;database:string;status:"RUNNING"|"PASS"|"FAIL";commands:Row[];summary:Row|null;errors:string[]}={phase:"R02",runId,database,status:"RUNNING",commands:[],summary:null,errors:[]};
function docker(args:string[],shown=args):string{const started=Date.now();try{const value=execFileSync("docker",args,{cwd:root,env,encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();evidence.commands.push({command:["docker",...shown],status:"PASS",elapsedMs:Date.now()-started});return value;}catch(error){evidence.commands.push({command:["docker",...shown],status:"FAIL",elapsedMs:Date.now()-started});throw error;}}
async function save(){await mkdir(resolve(root,"reports/gowm-v0.5"),{recursive:true});await writeFile(resolve(root,`reports/gowm-v0.5/r02-runtime-${runId}.json`),`${JSON.stringify(evidence,null,2)}\n`);}
let roleMade=false,proxyMade=false;let pool:Pool|undefined;
try{
 const container=docker(["compose","ps","--quiet","postgres"]);const networks=JSON.parse(docker(["inspect","--format","{{json .NetworkSettings.Networks}}",container])) as Row;const network=Object.keys(networks)[0];if(!network)throw new Error("network unavailable");
 docker(["compose","exec","--no-TTY","postgres","psql","--username","gowm","--dbname",database,"--set","ON_ERROR_STOP=on","--command",`CREATE ROLE ${role} LOGIN PASSWORD '${password}'; GRANT route_planner_provider TO ${role}`],["compose","exec","postgres","psql",`<create ${role} redacted>`]);roleMade=true;
 const proxyScript="import net from 'node:net';net.createServer(c=>{const u=net.connect(5432,'postgres');c.pipe(u).pipe(c);const x=()=>{c.destroy();u.destroy()};c.on('error',x);u.on('error',x)}).listen(5432,'0.0.0.0')";
 docker(["run","--detach","--name",proxy,"--network",network,"--publish","127.0.0.1::5432","node:22-bookworm","node","--input-type=module","--eval",proxyScript],["run","--detach","--name",proxy,"--network",network,"--publish","127.0.0.1::5432","node:22-bookworm","<fixed proxy>"]);proxyMade=true;
 const port=Number(docker(["inspect","--format","{{(index (index .NetworkSettings.Ports \"5432/tcp\") 0).HostPort}}",proxy]));pool=new Pool({host:"127.0.0.1",port,database,user:role,password,max:4,connectionTimeoutMillis:10_000});pool.on("error",()=>undefined);
 const adapter:NetworkSqlPool={async connect():Promise<NetworkSqlClient>{const client=await pool!.connect();return{async query<T extends Row=Row>(text:string,values?:readonly unknown[]){const result=await client.query(text,values===undefined?undefined:[...values]);return{rows:result.rows as T[],rowCount:result.rowCount};},release:()=>client.release()};}};
 const snapshot=await loadSnapshot(pool);const provider=createRoutePlanningProvider({pool:adapter,resultTtlMs:300_000});let counter=0;
 async function execute(operationId:string,input:Row){const descriptor=provider.runtime.manifest.capabilities.find(item=>item.operationId===operationId);if(!descriptor)throw new Error(`operation unavailable: ${operationId}`);const deadlineAt=new Date(Date.now()+60_000).toISOString();const request:ProviderExecutionRequest={providerProtocolVersion:"1.0",requestId:`r02_exec_${++counter}`,gatewayRequestId:`r02_gateway_${counter}`,idempotencyKey:`r02:${runId}:${counter}`,operation:{operationId:descriptor.operationId,operationVersion:descriptor.operationVersion,inputSchemaHash:descriptor.inputSchemaHash,outputSchemaHash:descriptor.outputSchemaHash},input,securityContext:{principalRef:"principal:r02",authenticationMethod:"RUNTIME_ACCEPTANCE",authenticatedAt:new Date(Date.now()-1000).toISOString(),dataScopeClaim:DATA_SCOPE,datasetScopeClaim:DATASET_SCOPE,scopeAttestation:{issuer:"r02",issuedAt:new Date().toISOString(),expiresAt:deadlineAt,claimDigest:sha256({runId})}},gatewayContext:{gatewayId:"r02",registryVersion:"v0.5",policyVersion:"r02"},executionPolicy:{deadlineAt,maximumInputBytes:1_048_576,maximumResultBytes:16_777_216,maximumCostClass:"HIGH"}};return (await provider.runtime.execute(request)).output!.value as Row;}
 const planned=await execute("route.plan",{requestId:`${runId}-plan`,routingSnapshot:snapshot,start:position(0.00025,0.02),destination:position(0.00175,0.02),travelProfile:"1",costProfile:"1",objective:"SHORTEST_DISTANCE",deadlineMs:30_000});assert(planned.status==="COMPLETED","route plan failed");
 const stale=await execute("route.verify",planned);assert(stale.status==="STALE","new condition/active graph did not mark pinned route STALE");
 const mutated=structuredClone(planned);const first=asRow(array(asRow(array(mutated.candidates)[0]).segments)[0]);first.distanceMm=Number(first.distanceMm)+1;const invalid=await execute("route.verify",mutated);assert(invalid.status==="INVALID","metric mutation was not rejected");
 evidence.summary={plannedStatus:planned.status,staleStatus:stale.status,invalidMetricStatus:invalid.status,pinnedGraph:snapshot.graphVersion,immutableResultHash:sha256(planned),checks:stale.checks};evidence.status="PASS";
 await pool.end();pool=undefined;docker(["rm","--force",proxy]);proxyMade=false;docker(["compose","exec","--no-TTY","postgres","psql","--username","gowm","--dbname","postgres","--command",`DROP ROLE ${role}`]);roleMade=false;await save();process.stdout.write(`GOWM_ROUTE_VERIFIER_RUNTIME_PASS ${runId} ${database}\n`);
}catch(error){evidence.status="FAIL";evidence.errors.push(String(error instanceof Error?error.stack??error.message:error));await save();throw error;}finally{await pool?.end().catch(()=>undefined);if(proxyMade)try{docker(["rm","--force",proxy]);}catch{}if(roleMade)try{docker(["compose","exec","--no-TTY","postgres","psql","--username","gowm","--dbname","postgres","--command",`DROP ROLE IF EXISTS ${role}`]);}catch{}}

async function loadSnapshot(target:Pool):Promise<Row>{const client=await target.connect();try{await client.query("BEGIN");await client.query("SELECT gowm_network_v1.set_scope($1,$2)",[DATA_SCOPE,DATASET_SCOPE]);const graph=(await client.query("SELECT graph_version,content_hash,dataset_version FROM gowm_network_v1.graph_version WHERE graph_version='p01-20260825t0610'")).rows[0];const profile=(await client.query("SELECT travel.version AS travel_version,cost.version AS cost_version,cost.content_hash FROM gowm_network_v1.travel_profile travel JOIN gowm_network_v1.cost_profile cost USING(travel_profile_version_id) WHERE travel.profile_key='p01-road-p01-20260825t0610' AND cost.profile_key='p01-cost-p01-20260825t0610'")).rows[0];const condition=(await client.query("SELECT condition_snapshot_id::text,content_hash FROM gowm_network_v1.condition_snapshot WHERE graph_version_id=(SELECT graph_version_id FROM gowm_network_v1.graph_version WHERE graph_version='p01-20260825t0610') AND source_snapshot_version='baseline'")).rows[0];await client.query("COMMIT");if(!graph||!profile||!condition)throw new Error("snapshot unavailable");return{networkDatasetVersion:graph.dataset_version,graphVersion:graph.graph_version,travelProfileVersion:profile.travel_version,costProfileVersion:profile.cost_version,conditionSnapshotId:condition.condition_snapshot_id,graphContentHash:graph.content_hash,costContentHash:profile.content_hash,conditionContentHash:condition.content_hash};}catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}}
function position(x:number,y:number):Row{return{coordinates:[x,y],crs:"EPSG:4326"};}function required(name:string){const value=process.env[name];if(!value)throw new Error(`${name} required`);return value;}function array(value:unknown):unknown[]{if(!Array.isArray(value))throw new Error("array expected");return value;}function asRow(value:unknown):Row{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("object expected");return value as Row;}function assert(value:unknown,message:string):asserts value{if(!value)throw new Error(message);}
