import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Pool } from "pg";
import type { ProviderExecutionRequest } from "../../packages/platform/contract-runtime/src/index.js";
import { sha256 } from "../../packages/platform/provider-sdk/src/index.js";
import { createRoutePlanningProvider } from "../../services/providers/route-planning-provider/src/provider.js";
import type { NetworkSqlClient, NetworkSqlPool, Row } from "../../services/providers/network-provider/src/types.js";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"../..");const DATA_SCOPE="n01-n01-20260825t0101";const DATASET_SCOPE="n01-acceptance";const runId=required("GOWM_V05_RUN_ID");const project=required("GOWM_V05_COMPOSE_PROJECT");const database=process.env.GOWM_R01_DATABASE??"gowm_v05_r00_20260825t0640";if(process.env.ALLOW_GOWM_ROUTE_PLANNING_GATE!=="YES")throw new Error("Set ALLOW_GOWM_ROUTE_PLANNING_GATE=YES");
const role=`r01_${runId.replaceAll("-","_")}`;const password=createHash("sha256").update(`${project}:${runId}:route`).digest("hex");const proxy=`gowm-${runId}-route-proxy`;const env={...process.env,COMPOSE_PROJECT_NAME:project,POSTGRES_PASSWORD:process.env.POSTGRES_PASSWORD??"gowm_v05_local_test",STAS_DB_PASSWORD:process.env.STAS_DB_PASSWORD??"gowm_v05_stas_local_test"};const evidence:{phase:string;runId:string;database:string;status:"RUNNING"|"PASS"|"FAIL";commands:Row[];summary:Row|null;errors:string[]}={phase:"R01",runId,database,status:"RUNNING",commands:[],summary:null,errors:[]};
function docker(args:string[],shown=args):string{const started=Date.now();try{const value=execFileSync("docker",args,{cwd:root,env,encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();evidence.commands.push({command:["docker",...shown],status:"PASS",elapsedMs:Date.now()-started});return value;}catch(error){evidence.commands.push({command:["docker",...shown],status:"FAIL",elapsedMs:Date.now()-started});throw error;}}
async function save(){await mkdir(resolve(root,"reports/gowm-v0.5"),{recursive:true});await writeFile(resolve(root,`reports/gowm-v0.5/r01-runtime-${runId}.json`),`${JSON.stringify(evidence,null,2)}\n`);}
let roleMade=false,proxyMade=false;let pool:Pool|undefined;
try{
 const container=docker(["compose","ps","--quiet","postgres"]);const networks=JSON.parse(docker(["inspect","--format","{{json .NetworkSettings.Networks}}",container])) as Row;const network=Object.keys(networks)[0];if(!network)throw new Error("network unavailable");
 docker(["compose","exec","--no-TTY","postgres","psql","--username","gowm","--dbname",database,"--set","ON_ERROR_STOP=on","--command",`CREATE ROLE ${role} LOGIN PASSWORD '${password}'; GRANT route_planner_provider TO ${role}`],["compose","exec","postgres","psql",`<create ${role} redacted>`]);roleMade=true;
 const script="import net from 'node:net';net.createServer(c=>{const u=net.connect(5432,'postgres');c.pipe(u).pipe(c);const x=()=>{c.destroy();u.destroy()};c.on('error',x);u.on('error',x)}).listen(5432,'0.0.0.0')";docker(["run","--detach","--name",proxy,"--network",network,"--publish","127.0.0.1::5432","node:22-bookworm","node","--input-type=module","--eval",script],["run","--detach","--name",proxy,"--network",network,"--publish","127.0.0.1::5432","node:22-bookworm","<fixed proxy>"]);proxyMade=true;const port=Number(docker(["inspect","--format","{{(index (index .NetworkSettings.Ports \"5432/tcp\") 0).HostPort}}",proxy]));
 pool=new Pool({host:"127.0.0.1",port,database,user:role,password,max:4,connectionTimeoutMillis:10_000});pool.on("error",()=>undefined);const adapter:NetworkSqlPool={async connect():Promise<NetworkSqlClient>{const client=await pool!.connect();return{async query<T extends Row=Row>(text:string,values?:readonly unknown[]){const r=await client.query(text,values===undefined?undefined:[...values]);return{rows:r.rows as T[],rowCount:r.rowCount};},release:()=>client.release()};}};
 const snapshot=await loadSnapshot(pool);const provider=createRoutePlanningProvider({pool:adapter,resultTtlMs:300_000});let counter=0;async function execute(input:Row){const d=provider.runtime.manifest.capabilities.find(x=>x.operationId==="route.plan")!;const deadlineAt=new Date(Date.now()+60_000).toISOString();const request:ProviderExecutionRequest={providerProtocolVersion:"1.0",requestId:`r01_exec_${++counter}`,gatewayRequestId:`r01_gateway_${counter}`,idempotencyKey:`r01:${runId}:${counter}`,operation:{operationId:d.operationId,operationVersion:d.operationVersion,inputSchemaHash:d.inputSchemaHash,outputSchemaHash:d.outputSchemaHash},input,securityContext:{principalRef:"principal:r01",authenticationMethod:"RUNTIME_ACCEPTANCE",authenticatedAt:new Date(Date.now()-1000).toISOString(),dataScopeClaim:DATA_SCOPE,datasetScopeClaim:DATASET_SCOPE,scopeAttestation:{issuer:"r01",issuedAt:new Date().toISOString(),expiresAt:deadlineAt,claimDigest:sha256({runId})}},gatewayContext:{gatewayId:"r01",registryVersion:"v0.5",policyVersion:"r01"},executionPolicy:{deadlineAt,maximumInputBytes:1_048_576,maximumResultBytes:16_777_216,maximumCostClass:"HIGH"}};return (await provider.runtime.execute(request)).output!.value as Row;}
 const base={routingSnapshot:snapshot,travelProfile:"1",costProfile:"1",objective:"SHORTEST_DISTANCE",deadlineMs:30_000};
 const coordinateInput={...base,requestId:`${runId}-coordinate`,start:position(0.00025,0.02),destination:position(0.00175,0.02)};const coordinate=await execute(coordinateInput);assert(coordinate.status==="COMPLETED"&&array(coordinate.candidates).length===1,"coordinate route failed");const coordinateReplay=await execute(coordinateInput);assert(sha256(coordinateReplay)===sha256(coordinate),"terminal route replay was not byte-equivalent");
 const waypoint=await execute({...base,requestId:`${runId}-waypoint`,start:position(0.0001,0.02),waypoints:[position(0.001,0.02)],destination:position(0.0019,0.02)});assert(waypoint.status==="COMPLETED"&&array(asRow(array(waypoint.candidates)[0]).segments).length>=2,"ordered waypoint failed");
 const avoidId=featureId("q");const avoid=await execute({...base,requestId:`${runId}-avoid`,start:position(0.0001,0),destination:position(0.0029,0),avoidReferences:[{namespace:"gowm",kind:"LAYER_FEATURE",id:avoidId,version:"1"}]});const segments=array(asRow(array(avoid.candidates)[0]).segments).map(asRow);assert(segments.every(s=>asRow(s.sourceFeatureReferenceKey).id!==avoidId),"avoid reference leaked");
 evidence.summary={manifestOperations:provider.runtime.manifest.capabilities.length,coordinateStatus:coordinate.status,coordinateResultHash:sha256(coordinate),exactTerminalReplay:true,waypointSegments:array(asRow(array(waypoint.candidates)[0]).segments).length,avoidSegments:segments.length,queryResultReferenceKey:coordinate.queryResultReferenceKey};evidence.status="PASS";await pool.end();pool=undefined;docker(["rm","--force",proxy]);proxyMade=false;docker(["compose","exec","--no-TTY","postgres","psql","--username","gowm","--dbname","postgres","--command",`DROP ROLE ${role}`]);roleMade=false;await save();process.stdout.write(`GOWM_ROUTE_PLANNING_RUNTIME_PASS ${runId} ${database}\n`);
}catch(error){evidence.status="FAIL";evidence.errors.push(String(error instanceof Error?error.stack??error.message:error));await save();throw error;}finally{await pool?.end().catch(()=>undefined);if(proxyMade)try{docker(["rm","--force",proxy]);}catch{}if(roleMade)try{docker(["compose","exec","--no-TTY","postgres","psql","--username","gowm","--dbname","postgres","--command",`DROP ROLE IF EXISTS ${role}`]);}catch{}}

async function loadSnapshot(pool:Pool):Promise<Row>{const c=await pool.connect();try{await c.query("BEGIN");await c.query("SELECT gowm_network_v1.set_scope($1,$2)",[DATA_SCOPE,DATASET_SCOPE]);const g=(await c.query("SELECT graph_version,content_hash,dataset_version FROM gowm_network_v1.graph_version WHERE graph_version='p01-20260825t0610'")).rows[0];const p=(await c.query("SELECT travel.travel_profile_version_id,travel.version AS travel_version,cost.version AS cost_version,cost.content_hash FROM gowm_network_v1.travel_profile travel JOIN gowm_network_v1.cost_profile cost USING(travel_profile_version_id) WHERE travel.profile_key='p01-road-p01-20260825t0610' AND cost.profile_key='p01-cost-p01-20260825t0610'")).rows[0];const s=(await c.query("SELECT condition_snapshot_id::text,content_hash FROM gowm_network_v1.condition_snapshot WHERE graph_version_id=(SELECT graph_version_id FROM gowm_network_v1.graph_version WHERE graph_version='p01-20260825t0610') AND source_snapshot_version='baseline'")).rows[0];await c.query("COMMIT");if(!g||!p||!s)throw new Error("snapshot unavailable");return{networkDatasetVersion:g.dataset_version,graphVersion:g.graph_version,travelProfileVersion:p.travel_version,costProfileVersion:p.cost_version,conditionSnapshotId:s.condition_snapshot_id,graphContentHash:g.content_hash,costContentHash:p.content_hash,conditionContentHash:s.content_hash};}catch(e){await c.query("ROLLBACK").catch(()=>undefined);throw e;}finally{c.release();}}
function position(x:number,y:number):Row{return{coordinates:[x,y],crs:"EPSG:4326"};}function featureId(label:string){return`wrf_${createHash("sha256").update(`p01:${label}`).digest("hex").slice(0,32)}`;}function required(name:string){const v=process.env[name];if(!v)throw new Error(`${name} required`);return v;}function array(v:unknown):unknown[]{if(!Array.isArray(v))throw new Error("array expected");return v;}function asRow(v:unknown):Row{if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("object expected");return v as Row;}function assert(v:unknown,m:string):asserts v{if(!v)throw new Error(m);}
