import { getContractSchema, type CapabilityDescriptor, type CapabilityProviderManifest } from "../../../../packages/platform/contract-runtime/src/index.js";
import { createProviderRuntime, sha256, type ProviderOperation, type ProviderRuntime } from "../../../../packages/platform/provider-sdk/src/index.js";
import { RoutePlanner, type RoutePlannerOptions } from "./planner.js";

const OPERATIONS = ["route.validate","route.plan","route.plan-alternatives","route.verify"] as const;
type RouteOperation = (typeof OPERATIONS)[number];
const REQUEST_HASH="sha256:0cdee0b4a503099aef05e738a323ae57414c7f0c9cdba7997f86e89ed045da67" as const;
const RESULT_HASH="sha256:e45253b2c53dfe6d40be0bdbc7cf4c33fb5d9500bff3363da2ee27da96418f8c" as const;
const VERIFY_HASH="sha256:76477a2cf770bb5a72208882aa841ac7b13f60e0516a4726ff265efcbdbea8bd" as const;

export interface RoutePlanningProvider { runtime: ProviderRuntime; planner: RoutePlanner; }
export function createRoutePlanningProvider(options: RoutePlannerOptions): RoutePlanningProvider {
  const planner=new RoutePlanner(options); const operations=OPERATIONS.map((id)=>operation(id,planner));
  const manifest:CapabilityProviderManifest={providerProtocolVersion:"1.0",provider:{providerId:"gowm.route-planning",providerVersion:"1.0.0",owner:"gowm-platform",implementationDigest:sha256({provider:"gowm.route-planning",version:"1.0.0",readContract:"gowm_network_v1",runtime:"route_planner_runtime",operations:operations.map(({descriptor})=>descriptor.operationId)}),sourceRef:"urn:gowm:source:in-tree:route-planning-provider:1.0.0"},endpoints:{manifest:"/v1/manifest",liveness:"/health/live",readiness:"/health/ready",execute:"/v1/operations/{operationId}:execute",job:"/v1/jobs/{jobId}"},capabilities:operations.map(({descriptor})=>descriptor)};
  return {planner,runtime:createProviderRuntime({manifest,operations,policyVersion:"gowm-route-planning-policy/1.0",policyDigest:sha256({networkReadContract:"gowm_network_v1",runtime:"route_planner_runtime",productState:true,independentVerification:true})})};
}
function operation(id:RouteOperation,planner:RoutePlanner):ProviderOperation{
  const requestInput=id!=="route.verify"; const verifyOutput=id==="route.validate"||id==="route.verify"; const inputUri=`urn:gowm:v0.5:${requestInput?"route-planning-request":"route-planning-result"}`; const outputUri=`urn:gowm:v0.5:${verifyOutput?"route-verification-report":"route-planning-result"}`; const inputHash=requestInput?REQUEST_HASH:RESULT_HASH; const outputHash=verifyOutput?VERIFY_HASH:RESULT_HASH; const preview=id==="route.plan-alternatives"; const async=id==="route.plan"||preview;
  const descriptor:CapabilityDescriptor={operationId:id,operationVersion:"1.0",semanticRole:"DOMAIN_ANALYSIS",dataBinding:"WORLD_SNAPSHOT_BOUND",resultSemantics:verifyOutput?"VALIDATION":"DERIVED_ANALYSIS",executionBindings:["SYNC_HTTP","VERSIONED_SQL_CONTRACT",...(async?["ASYNC_JOB" as const]:[])],criticalPathPolicy:"REMOTE_ONLY",maturity:preview?"PREVIEW":"STABLE",inputSchemaUri:inputUri,inputSchemaHash:inputHash,outputSchemaUri:outputUri,outputSchemaHash:outputHash,scopePolicy:"DATA_SCOPE_REQUIRED",execution:{mode:async?"SYNC_OR_ASYNC":"SYNC",defaultTimeoutMs:30_000,maximumTimeoutMs:300_000,costClass:"HIGH"},limits:{maximumInputBytes:1_048_576,maximumOutputBytes:16_777_216,maximumRows:100_000,maximumCandidates:128,maximumBatchItems:100},snapshotPolicy:{dataSnapshot:"REQUIRED",computeSnapshot:"REQUIRED"},ports:{inputs:[{name:"request",schemaUri:inputUri,schemaHash:inputHash,valueKind:"ANY",unitSemantics:"UNSPECIFIED"}],outputs:[{name:"result",schemaUri:outputUri,schemaHash:outputHash,valueKind:"ANY",unitSemantics:"UNSPECIFIED"}]}};
  return {descriptor,inputSchema:getContractSchema(inputUri),outputSchema:getContractSchema(outputUri),inputSchemaLockHash:inputHash,outputSchemaLockHash:outputHash,method:{engine:"GOWM Product-State Route Planner",engineVersion:"1.0",methodId:`gowm-route-planning/${id}`,methodVersion:"1.0",artifacts:[{kind:"DATABASE",name:"gowm_network_v1+route_planner_runtime",version:"migration-046"}]},async handle(input,context){const dataScopeKey=context.security.dataScopeClaim;const datasetScopeKey=context.security.datasetScopeClaims?.[0];const scope={...(dataScopeKey===undefined?{}:{dataScopeKey}),...(datasetScopeKey===undefined?{}:{datasetScopeKey})};const result=id==="route.validate"?await planner.validate(input,scope,context.deadline.remainingMs()):id==="route.verify"?await planner.verify(input,scope,context.deadline.remainingMs()):await planner.plan(input,scope,context.deadline.remainingMs(),preview);return{status:"COMPLETED",value:result.output,dataSnapshot:result.dataSnapshot,consumption:{rows:result.rows,candidates:result.candidates},warnings:[],changes:{repairApplied:false,typeChanged:false}};}};
}
