export type HistoricalOutcomeStatus = "COMPLETED" | "PARTIAL" | "NO_DATA" | "INDETERMINATE";

export type HistoricalFinalizationState = "PROVISIONAL" | "SEALED" | "CONFLICTED";

export interface HistoricalOutcome {
  status: HistoricalOutcomeStatus;
  reasonCode: string;
  warnings: string[];
}

export const HISTORICAL_OUTCOME_REASON = {
  COMPLETE: "HISTORICAL_TRAJECTORY_COMPLETE",
  PARTIAL_COVERAGE: "PARTIAL_TEMPORAL_COVERAGE",
  UNKNOWN_GAPS: "UNKNOWN_GAPS_PRESENT",
  NO_TRAJECTORY_POINTS: "NO_TRAJECTORY_POINTS",
  INVALID_REQUEST_DURATION: "INVALID_REQUEST_DURATION",
  SOURCE_CONFLICT: "SOURCE_SELECTION_CONFLICT",
  INTERVAL_CONFLICT: "TASK_INTERVAL_CONFLICT",
  NO_SOURCE_CANDIDATE: "NO_SOURCE_CANDIDATE",
  MULTIPLE_SOURCE_CANDIDATES: "MULTIPLE_SOURCE_CANDIDATES",
  MULTIPLE_TRACKER_SESSIONS: "MULTIPLE_TRACKER_SESSIONS",
  MULTIPLE_TRACKLET_VERSIONS: "MULTIPLE_TRACKLET_VERSIONS",
  ENTITY_BINDING_CONFLICT: "ENTITY_BINDING_CONFLICT",
  ANALYSIS_SPACE_CONFLICT: "ANALYSIS_SPACE_CONFLICT"
} as const;
